### ISSUE TITLE
Project with path ':app' could not be found in project ':test'

### ISSUE THREAD

**Issue by sek** [dsheikherev/separate_test_module#1]
Thanks for posting a sample project!

I am hitting an error that I wonder how you got around?

git clone https://github.com/dsheikherev/separate_test_module.git
cd separate_test_module
git checkout as_separate_project
cd BasicSampleTests
gradle --version        # Gradle 4.5.1
gradle test:assembleDebug

    ...
    FAILURE: Build failed with an exception.

    * What went wrong:
    A problem occurred configuring project ':test'.
    > Project with path ':app' could not be found in project ':test'.

If I remove `targetProjectPath ':app'` from BasicSampleTests/test/build.gradle then I get an error that it's required

    > targetProjectPath cannot be null in test project test

**Comment by sek** [comment]
Got separate test project working by having an empty :app module just to make gradle happy and then launching the separate app like:

    Context context = InstrumentationRegistry.getContext();
    context.startActivity(context.getPackageManager().getLaunchIntentForPackage("some.other.apps.package"));

Then can use any UIAutomator methods that don't directly reference the code of the application project, ex:

    BySelector selector = By.text("Button");
    device.wait(Until.hasObject(selector), 2000L);
    device.findObject(selector).click();

**Comment by SGA-abmajid-nurulaiman** [comment]
> Got separate test project working by having an empty :app module just to make gradle happy and then launching the separate app like:
> 
> ```
> Context context = InstrumentationRegistry.getContext();
> context.startActivity(context.getPackageManager().getLaunchIntentForPackage("some.other.apps.package"));
> ```
> 
> Then can use any UIAutomator methods that don't directly reference the code of the application project, ex:
> 
> ```
> BySelector selector = By.text("Button");
> device.wait(Until.hasObject(selector), 2000L);
> device.findObject(selector).click();
> ```

@sek, but then, you need to install the app module APK in order for the com.example.android.testing.espresso.BasicSample.tests APK to work, isn't it?

tried your way & getting this error:
`$ adb shell am instrument -w -r com.example.android.testing.espresso.BasicSample.tests/androidx.test.runner.AndroidJUnitRunner
onError: commandError=true message=INSTRUMENTATION_FAILED: com.example.android.testing.espresso.BasicSample.tests/androidx.test.runner.AndroidJUnitRunner
android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.android.testing.espresso.BasicSample.tests/androidx.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Instrument.run(Instrument.java:486)
        at com.android.commands.am.Am.runInstrument(Am.java:194)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation target package: com.example.android.testing.espresso.BasicSample.app
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0xaafbd0b4)
`
